### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by marcelm** [FrickTobias/BLR#21]
I am collecting here some ideas for how to improve the performance of the pipeline.

* [X] On UPPMAX, `/scratch/` should be used for temporary files. It is faster than writing to the network file system. (See #115)
* [ ] More streaming should be employed. Currently, many huge intermediate FASTQ files are generated, some uncompressed, some compressed. This is slow: When writing them uncompressed, file I/O performance is likely a bottleneck. When writing them compressed, that takes a lot of CPU hours. Instead, one can let one program write uncompressed and send the output to the next program via a pipe. This avoids the intermediate file to disk entirely.
* [x] The `bc_extract.py` script should be rewritten so that it can work in a streaming fashion.
* [x] It should be possible to combine the last two Cutadapt commands into one.
* [x] Check whether it is faster to run multiple CD-HITs in parallel (instead of giving each CD-HIT the full number of cores).
* [x] Check whether a different clustering method (perhaps a custom one) is faster than CD-HIT (see #109)
* [x] Avoid the intermediate `samtools view` step (SAM can be piped directly into `samtools sort`).
* [x] Use FIFO tricks to run `samtools index` at the same time as generating the BAM that is being indexed. Again, this avoids I/O.
* [x] Test other read mappers (BWA-MEM, minimap2) (See #111 and #112)
* [x] Test alternatives to MarkDuplicates (`sambamba markdup`, `samblaster`) (Moved to #113)

**Comment by marcelm** [comment]
A full pipeline run on a 29+40GB dataset (using 20 cores):

Stage | Wall-clock time (minutes) | Percentage
--- | ---: | ---:
Cutadapt 1  | 40 | 0.98%|
Barcode extraction  | 120 | 2.93%
Cutadapt 2  | 70 | 1.71%
Cutadapt 3  | 65 | 1.59%
Clustering preparation  | 45 | 1.10%
Clustering  | 900 | 21.98%
Read mapping  | 600 | 14.65%
BAM sorting  | 255 | 6.23%
BAM tagging  | 260 | 6.35%
Duplicate removal  | 300 | 7.33%
Duplicate marking  | 170 | 4.15%
Cluster merging  | 780 | 19.05%
BAM indexing  | 10 | 0.24%
Cluster filtering  | 240 | 5.86%
FASTQ generation  | 240 | 5.86%
**Total** | **4095** | 100.00%

**Comment by FrickTobias** [comment]
Everything seems reasonable to implement without any problems. I'll start looking into it.

Regarding the barcode clustering, it is currently divided into subproblems by assuming the first three bases does not contain sequencing errors and splitting them into separate files accordingly (e.g. one file for AAA-17N, one file for AAC-17N etc). I think it makes more sense to be able to cluster them without using the indexing first, before trying to run them in parallel but I've been unsuccessful to do that (although this depends on the kind of library since they generate drastically different number of barcodes). 

My impression was that CD-HIT has been a quite fast clustering algorithm for our purposes (since we don't have any whitelist) but if there is a faster one that'd be great. Especially since CD-HIT employs k-mer based clustering which shouldn't be optimal since the errors we correct for are randomly distributed.

**Comment by pontushojer** [comment]
### Investigation into running cd-hit in parallel instead of giving multiple cores
#### Test files
Took: barcode file TTT.fa from 190416.HiSeq.emTn5.Next.reseq_3.VII-XI_XVII.SM10.reseq_2 split into four files. Below is `wc -l` of files. 
```
  38792 TTTA.fa
  37770 TTTC.fa
  46864 TTTG.fa
    412 TTTT.fa
```

#### Tests
Serial: Run each file on 4 threads on after the other
Parallel: Run each file in parallel on 1 thread each.

Use `time` to check execution.

#### Results
Both scripts produced the same clusters for each file.

1. `time` execution
1.1 Running in serial:

time bash run_serial.sh | Run 1 | Run 2 | Run 3 | Mean (sec)
---|---:|---:|---:|---:
real | 38.6 | 44.4 | 48.1 | 43.7
user | 20.1 | 20.4 | 20.2 | 20.3
sys | 0.9 | 0.9 | 1.0 | 0.9

1.2 Running in parallel:

time bash run_parallel.sh | Run 1 | Run 2 | Run 3 | Mean (sec)
---|---:|---:|---:|---:
real | 5.4 | 5.7 | 6.1 | 5.7
user | 0.8 | 0.8 | 0.8 | 0.8
sys | 0.6 | 0.6 | 0.5 | 0.6


2. cd-hit log file 'Total CPU time'
2.1 Running in serial:

Cdhit reported time | Run 1 | Run 2 | Run 3 | Mean (sec)
-- | --: | --: | --: | --:
TTTA.fa | 5.4 | 5.6 | 5.5 | 5.5
TTTC.fa | 5.4 | 5.7 | 5.6 | 5.6
TTTG.fa | 8.8 | 8.6 | 8.6 | 8.7
TTTT.fa | 0.1 | 0.1 | 0.1 | 0.1

2.2 Running in parallel:

Cdhit reported time | Run 1 | Run 2 | Run 3 | Mean (sec)
-- | --: | --: | --: | --:
TTTA.fa | 5.7 | 5.3 | 5.4 | 5.5
TTTC.fa | 5.2 | 5.2 | 5.1 | 5.1
TTTG.fa | 8.8 | 8.5 | 8.6 | 8.6
TTTT.fa parallel | 0.0 | 0.0 | 0.0 | 0.0


#### Conclusion
Real runtime for serial execution is much slower.  

Similar cd-hit cluster time for 4 vs 1 (parallel job) thread --> more value from running in parallel.

#### Scripts
Script: run_serial.sh
```
for i in {"TTTA","TTTG","TTTC","TTTT"}; do
        printf "File: $i.fa"
        cd-hit-454 -i $i".fa" -o $i".clustered" -T 4 -c 0.9 -gap 100 -g 1 -n 3 -M 0 >> $i"run_serial.log" 
done
```

Script_ run_parallel.sh
```
for i in {"TTTA","TTTG","TTTC","TTTT"}; do
        printf "File: $i.fa"
        cd-hit-454 -i $i".fa" -o $i".clustered" -T 1 -c 0.9 -gap 100 -g 1 -n 3 -M 0 >> $i"run_parallel.log" & 
done
````

**Comment by FrickTobias** [comment]
Regarding testing other mappers we've noticed the mapper [emerald](https://github.com/statgen/emeraLD) which is based on bwa and is barcode-aware which we think look promising after reading their [paper](https://doi.org/10.1093/bioinformatics/bty547).

**Comment by pontushojer** [comment]
> Regarding testing other mappers we've noticed the mapper [emerald](https://github.com/statgen/emeraLD) which is based on bwa and is barcode-aware which we think look promising after reading their [paper](https://doi.org/10.1093/bioinformatics/bty547).

I am currently testing it and bwa

**Comment by marcelm** [comment]
Closing this one as some of the things have been implemented and the rest is now being track in separate issues.
